server:
  port: 8080

spring:
  application:
    name: url-shortner


  datasource:
    url: jdbc:postgresql://localhost:5432/url
    password: postgres
    username: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
#        default_schema: url

  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GIT_CLIENT_ID}
            client-secret: ${GIT_CLIENT_SECRET}
            scope:
              - read:user
              - user:email

          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}

logging:
  #    file:
  #      path: logs/
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
  #      file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    web: error
    root: info
    sql: error

#url
url:
  prefix: http://localhost:8080/c2s/


#Secret Key
Secret:
  key: fkgnkvbkdfgrthgsfvfghjgnfdhguigndfjvkndffdkngdfkj