server:
  port: 8080

spring:
  application:
    name: url-shortner


  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    password: postgres
    username: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

logging:
  #    file:
  #      path: logs/
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
  #      file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    web: error
    root: info
    sql: error

#url
url:
  prefix: jskool.jh/