spring:
  datasource:
    url: jdbc:postgresql://ep-lively-unit-a1pvq2yh-pooler.ap-southeast-1.aws.neon.tech:5432/neondb?sslmode=require
    username: neondb_owner
    password: ${PASSWORD}
    driver-class-name: org.postgresql.Driver

server:
  forward-headers-strategy: framework


cors:
  url: https://cut2short-front.onrender.com

#callback:
#  url: https://cut2short-front.onrender.com/oauth2/callback

callback:
  url: https://cut2short-front.onrender.com/dashboard

app:
  base-url: https://cut2short-backend.onrender.com/c2s/