server:
  port: 8080
  servlet:
    session:
      cookie:
        same-site: none
        secure: true

spring:
  application:
    name: cut2short
  profiles:
    active: dev

  threads:
    virtual:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
        cache:
          use_second_level_cache: true
          region:
            factory_class: org.hibernate.cache.jcache.JCacheRegionFactory
          use_query_cache: true
      javax:
        cache:
          provider: org.ehcache.jsr107.EhcacheCachingProvider
          uri: classpath:ehcache.xml
    open-in-view: false
  #          default_schema: url

  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GIT_CLIENT_ID}
            client-secret: ${GIT_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-name: GitHub
            scope:
              - read:user
              - user:email

          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: profile, email
        provider:
          google:
            authorization-uri:  https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user

#  mail:
#    username: ${USERNAME}
#  sendgrid:
#    api-key: ${API_KEY}

logging:
  #    file:
  #      path: logs/
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
  #      file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    web: error
    root: info
    sql: error
    org:
      hibernate:
        sql: debug
        cache:
          spi: debug
        type:
          descriptor:
            sql:
              BasicBinder: trace

#url
url:
  prefix: https://cut2short-backend.onrender.com/c2s/

jwt:
  expiration: 86400000
  secret: fkgnkvbkdfgrthgsfvfghjgnfdhguigndfjvkndffdkngdfkj

#Secret Key
#Secret:
#  key: fkgnkvbkdfgrthgsfvfghjgnfdhguigndfjvkndffdkngdfkj